### ISSUE TITLE
Would it be possible to add fast forward/rewind functionality?

### ISSUE THREAD

**Issue by ghostknow** [LondonX/Beryllium#15]
Some m3u8 files are for on-demand videos, rather than live streams. 
Is it possible to add fast forward/rewind functionality for these files?
Thanks

**Comment by LondonX** [comment]
Of course you can.
just add branches in `onKeyDown` of `MainActivity.kt` to call [seekTo](https://developer.android.com/reference/android/media/MediaPlayer#seekTo%28long,%20int%29).

And happy coding 😊
